# Site settings
title: Al Crowley - Professional Portfolio
email: albert.crowley@tcg.com
description: >-
  My public speaking portfolio, technical papers, and blog posts.
baseurl: "/portfolio" # Replace with your repo name
url: "https://albertcrowley.github.io"

# Theme Configuration
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
