# Site settings
title: Al Crowley - Professional Portfolio
email: albert.crowley@tcg.com
description: >-
  My public speaking portfolio, technical papers, and blog posts.
baseurl: "/portfolio" # Replace with your repo name
url: "https://albertcrowley.github.io"

# Theme Configuration

theme: jekyll-theme-dinky